config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :users, only: %i[ show edit update index ] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end

  resources :diseases do
    resources :treatments
    resources :expenses 
    resources :comments, only: %i[create destroy edit update]
    collection do
      get 'search'
    end
  end
  resources :onsets, only: %i[create destroy index]
  resources :events
  resources :simulations
  
  post '/diseases/guest_sign_in', to: 'diseases#guest_sign_in'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/onset.rb
class Onset < ApplicationRecord
  belongs_to :user
  belongs_to :disease
end

app/controllers/onsets_controller.rb
class OnsetsController < ApplicationController
  before_action :authenticate_user!
   
  def index
    @onsets = current_user.onsets
  end

  def create
    onset = current_user.onsets.create(disease_id: params[:disease_id])
    redirect_to disease_url(onset.disease_id), notice: "#{onset.disease.name}を登録しました"
  end

  def destroy
    onset = current_user.onsets.find_by(id: params[:id]).destroy
    redirect_to disease_url(onset.disease_id), notice: "#{onset.disease.name}を登録解除しました"
  end
end

app/helpers/onsets_helper.rb
module OnsetsHelper
end

app/views/onsets/index.html.erb
  <h3 style="text-align:center">登録疾患名</h3>
  <div style="text-align:center">
    <%= link_to " 疾患一覧", diseases_path,id: @disease ,class:"btn btn-primary btn-lg fas fa-file-medical "%>
  </div>
  <br>
  <% @onsets.sort_by {|onset| onset.disease_id}.each do |onset|%>
  <br>
  <h5 style="text-align:center">告示番号<%=link_to onset.disease.number,disease_url(onset.disease_id) %></h5>
  <h2 style="text-align:center"><%=link_to onset.disease.name,disease_url(onset.disease_id) %></h2>
  <% end %>
  <br>
  <p style="text-align:center">
    <%= link_to '戻る', user_path(current_user.id) %>
  </p>