config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :users, only: %i[ show edit update index ] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end

  resources :diseases do
    resources :treatments
    resources :expenses 
    resources :comments, only: %i[create destroy edit update]
    collection do
      get 'search'
    end
  end
  resources :onsets, only: %i[create destroy index]
  resources :events
  resources :simulations
  
  post '/diseases/guest_sign_in', to: 'diseases#guest_sign_in'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :onsets, dependent: :destroy
  has_many :onset_diseases, through: :onsets, source: :disease
  has_many :comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :treatments, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  mount_uploader :image, ImageUploader

  validates :name, presence: true, length: { in: 1..10 }
  validates :self_introduction, length: { in: 1..1000 }

  enum prefecture:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }
  validates :prefecture, inclusion: { in: User.prefectures.keys[1..47] }

  enum age:{
    "-----":1,
    "10歳未満":2,"10代":3,"20代":4,"30代":5,"40代":6,"50代":7,"60代":8,"70代":9,"80代":10,"90代以上":11
  }
  validates :age, inclusion: { in: User.ages.keys[1..11] }

  enum classification:{
    "----":0,
    本人:1,家族:2,親戚:3,友人:4,恋人:5,患者団体:6,医師:7,薬剤師:8,看護師:9,その他医療従事者:10
  }

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
      user.admin = false
      user.name = "ゲスト"
      user.age = "30代"
      user.birthday = "2022-02-22"
      user.prefecture = "東京都"
      user.self_introduction =  "ゲストです。"
      user.classification =  "本人"

    end
  end

  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
      user.admin = true
      user.name = "ゲスト管理者"
      user.age = "30代"
      user.birthday = "2022-01-01"
      user.prefecture = "東京都"
      user.self_introduction =  "ゲスト管理者です。"
      user.classification =  "本人"
    end
  end

  def onset(disease)
    onsets_diseases << disease
  end

  def unonset(disease)
    onsets_diseases.destroy(disease)
  end
  
  # お気に入りしているかどうか
  def onsets?(disease)
    onsets.where(disease_id: :disease.id).exists?
  end

  #指定のユーザをフォローする
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  #フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  
  #指定のユーザのフォローを解除する
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com' || params[:user][:email].downcase == 'admin_guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy edit]

  def ensure_normal_user
    if resource.email == 'guest@example.com' || resource.email == 'admin_guest@example.com'
      redirect_to root_path,
                  alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def admin_guest_sign_in
    user = User.admin_guest
    sign_in user
    redirect_to rails_admin_path, notice: 'ゲスト管理者ユーザーとしてログインしました。'
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[ profile edit update index]
  before_action :set_user, only: %i[show edit update]
  before_action :prohibit_access, only: %i[edit update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
    redirect_to user_path(@user) unless @user == current_user
  end
  
  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user), notice: "プロフィールを更新しました"
    else
      redirect_to edit_user_path(current_user), alert: "アカウント名(10文字以内)、メールアドレス、年齢、エリアは必ず入力してください"
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :birthday, :prefecture, :self_introduction, :image, :image_cache, :classification, :age)
  end

  def prohibit_access
    redirect_to  root_path, alert: 'アクセス権がありません' unless @user.id == current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form_<%= user.id %>" , class="actions">
  <% unless current_user.following?(user) %>
  <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
  <%= f.hidden_field :followed_id %>
  <div style="text-align:center"><%= f.submit "フォロー", class: 'btn btn-primary follow' %></div>
  <% end %>
  <% else %>
  <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
  <div style="text-align:center"><%= f.submit "フォロー解除", class: 'btn btn-warning follow' %></div>
  <% end %>
  <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
<% if user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="user_field">
  <%= form.label :image %>
  <%= form.file_field :image %>
  <% unless @user.image.blank? %>
  <%= image_tag @user.image.url, size: '150x150' %>
  <% end %>
</div>

<div class="user_field">
  <%= form.label :email %>
  <%= form.text_field :email %>
</div>

<div class="user_field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="user_field">
  <%= form.label :age %>
  <%= form.select :age, User.ages.keys, {} %>
</div>

<div class="user_field">
  <%= form.label :birthday %>
  <%= form.date_select :birthday, {start_year:Time.now.year-100, end_year:Time.now.year} %>
</div>

<div class="user_field">
  <%= form.label :prefecture %>
  <%= form.select :prefecture, User.prefectures.keys, {} %>
</div>

<div class="user_field">
  <%= form.label :self_introduction %>
  <%= form.text_area :self_introduction %>
</div>

<div class="user_field">
  <%= form.label :classification %>
  <%= form.select :classification, User.classifications.keys, {} %>
</div>
<br>
<div class="actions">
  <%= form.submit %>
</div>
<% end %>
<br>
<p style="text-align:center">
  <%= link_to '戻る', user_path(current_user.id) %>
</p>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats" , style="text-align:center">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/edit.html.erb
<h3 style="text-align:center">プロフィール編集</h3>

<%= render 'form', user: @user %>

<%= link_to 'Back', user_path(current_user) %>

app/views/users/index.html.erb
<h1>User一覧</h1>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th nowrap scope="col">名前</th>
      <th nowrap scope="col">年齢</th>
      <th nowrap scope="col">エリア</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.age %></td>
      <td><%= user.prefecture %></td>
      <%# <td><%= link_to '編集', edit_user_path(user) %>
      <%# <td><%= link_to '削除', user, method: :delete, data: { confirm: 'のエラーがあります' } %>
      <td> <%= render 'follow_form', user: user %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%# <%= link_to 'New User', new_user_path %>
<%= link_to 'ホーム', root_path %>

<h2>ユーザー</h2>
<% @users.each do |user| %>
<% if user.id != current_user.id %>
<li>
  <div class="item">
    <%= link_to user.name, user %>
    <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
  </div>
</li>
<li><%= render 'follow_form', user: user %></li> <!-- フォロー機能が実装されて入ればこの一文も必要 -->
<% end %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<% if user_signed_in? && @user == current_user %>
<h2 style="text-align:center"><%= @user.name %>さんのマイページ</h2>
<% else %>
<h2 style="text-align:center"><%= @user.name %>さんのページ</h2>
<% end %>
<br>
<div>
  <div class="flame09">
    <% if @user.image.blank? %>
    <div style="text-align:center">
      <img src="/assets/icon1.png" width="150" height="150">
    </div>
    <% else%>
    <div style="text-align:center">
      <%= image_tag @user.image.url, size: '150x150' %>
    </div>
    <% end %>

    <%# メッセージ　%>
    <% if @user.id != current_user.id %>
    <p style="text-align:center">
      <%= link_to '', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post, class:"btn btn-info btn-lg fas fa-envelope "%>
    </p>
    <p><%= render 'follow_form', user: @user %></p>

    <%end%>
    <%# メッセージ一覧　%>
    <% if @user.id == current_user.id %>
    <p style="text-align:center">
      <%= link_to '',conversations_path, class:"btn btn-info btn-lg fas fa-envelope " %>
      <%= render 'stats' %></p>
    <% end %>
  </div>


  <%# 修正予定！ 各Userごとの登録疾患を表示%>
  <% if @user.id == current_user.id%>
  <p style="text-align:center">
    <%= link_to ' 登録した疾患', onsets_path,id: @disease ,class:"btn far fa-calendar-plus "%>
  </p>
  <%end%>

  <p style="text-align:center">
    <strong class="user_strong">名前:</strong>
    <span class="user_a"><%= @user.name %></span>
  </p>

  <p style="text-align:center">
    <strong class="user_strong">メールアドレス:</strong>
    <span class="user_a"><%= @user.email %></span>
  </p>

  <p style="text-align:center">
    <strong class="user_strong">年齢:</strong>
    <span class="user_a"><%= @user.age %></span>
  </p>

  <p style="text-align:center">
    <strong class="user_strong">エリア:</strong>
    <span class="user_a"><%= @user.prefecture %></span>
  </p>

  <p style="text-align:center">
    <strong class="user_strong">生年月日:</strong>
    <span class="user_a"><%= @user.birthday.strftime("%Y年%m月%d日") unless @user.birthday.blank? %></span>
  </p>

  <p style="text-align:center">
    <strong class="user_strong">自己紹介:</strong>
    <span class="user_a"><%= @user.self_introduction %></span>
  </p>


  <p style="text-align:center">
    <strong class="user_strong">関係区分:</strong>
    <span class="user_a"><%= @user.classification %></span>
  </p>
</div>

<%# userとdisease.idをリレーションする%>
<%#= link_to '一覧', users_path %>
<p style="text-align:center">
  <% if user_signed_in? && @user == current_user %>
  <%= link_to '戻る', root_path %>/
  <%= link_to "プロフィール編集", edit_user_path(current_user) %>
  <% end %>
</p>

app/views/users/show_follow.html.erb
<h2 style="text-align:center"><%= @user.name %>さんのフォローリスト</h2>
<% if @user.following.blank? %>
<h5 style="text-align:center">フォローやメッセージをすると繋がりが広がります</h5>
<% elsif %>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th nowrap scope="col"></th>
      <th nowrap scope="col">名前</th>
      <th nowrap scope="col">年齢</th>
      <th nowrap scope="col">エリア</th>
    </tr>
  </thead>
  <tbody>
    <% @user.following.each do |user| %>
    <tr>
      <% if user.image.blank? %>
      <td> <img src="/assets/icon1.png" width="90" height="90">
        <%else %>
      <td nowrap width=15%> <img src=<%= user.image %> width="90" height="90">
        <% end %>
      <td> <%= link_to user.name, user_path(user) %> </td>
      <td> <%= user.age %> </td>
      <td> <%= user.prefecture %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%end%>

app/views/users/show_follower.html.erb
<h2 style="text-align:center"><%= @user.name %>さんのフォロワーリスト</h2>
<% if @user.followers.blank? %>
<h5 style="text-align:center">フォローやメッセージをすると繋がりが広がります</h5>
<% elsif %>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th nowrap scope="col"></th>
      <th nowrap scope="col">名前</th>
      <th nowrap scope="col">年齢</th>
      <th nowrap scope="col">エリア</th>
    </tr>
  </thead>
  <tbody>
    <% @user.followers.each do |user| %>
    <tr>
      <% if user.image.blank? %>
      <td> <img src="/assets/icon1.png" width="90" height="90">
        <%else %>
      <td nowrap width=15%> <img src=<%= user.image %> width="90" height="90">
        <% end %>
      <td> <%= link_to user.name, user_path(user) %> </td>
      <td> <%= user.age %> </td>
      <td> <%= user.prefecture %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%end%>