config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :users, only: %i[ show edit update index ] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end

  resources :diseases do
    resources :treatments
    resources :expenses 
    resources :comments, only: %i[create destroy edit update]
    collection do
      get 'search'
    end
  end
  resources :onsets, only: %i[create destroy index]
  resources :events
  resources :simulations
  
  post '/diseases/guest_sign_in', to: 'diseases#guest_sign_in'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_disease, only: %i[ show edit update destroy ]
  before_action :set_q, only: %i[index search]
  before_action :prohibit_access, only: %i[ new create edit update destroy ]

  def index
    @diseases = Disease.page(params[:page]).per(10)
  end

  def show
    @comments = @disease.comments.page(params[:page]).per(10)
    @comment = @disease.comments.build
    @onset = current_user.onsets.find_by(disease_id: @disease.id)
  end

  def new
    @disease = Disease.new
  end

  def edit
  end

  def create
    @disease = Disease.new(disease_params)
    respond_to do |format|
      if @disease.save
        format.html { redirect_to disease_url(@disease) }
        format.json { render :show, status: :created, location: @disease }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @disease.update(disease_params)
        format.html { redirect_to disease_url(@disease)}
        format.json { render :show, status: :ok, location: @disease }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @disease.destroy

    respond_to do |format|
      format.html { redirect_to disease_url }
      format.json { head :no_content }
    end
  end

  def search
    @results = @q.result
  end

  private
  def set_q
    @q = Disease.ransack(params[:q])
  end

  def set_disease
    @disease = Disease.find(params[:id])
  end

  def disease_params
    params.require(:disease).permit(:id, :name, :number)
  end

  def prohibit_access
    redirect_to  root_path, alert: 'アクセス権がありません' unless current_user.admin?
  end
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/views/diseases/_form.html.erb
<%= form_with(model: disease, local: true) do |form| %>
<div style="text-align:center">
  <% if disease.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(disease.errors.count, "件") %> のエラーがあります</h2>

    <ul>
      <% disease.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="user_field">
  <%= form.label :number %>
  <%= form.text_field :number %>
</div>

<div class="user_field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<br>
<div class="actions">
  <%= form.submit %>
</div>
<br>
<% end %>

app/views/diseases/edit.html.erb
<h1>Editing Disease</h1>

<%= render 'form', disease: @disease %>

<div style="text-align:center">
  <%= link_to '詳細', @disease %> |
  <%= link_to '戻る', diseases_path %>
</div>

app/views/diseases/index.html.erb
<h2 style="text-align:center">病名検索</h2>

<div class="parent">
  <dl class="searchbox ">
    <%= search_form_for @q, url: search_diseases_path do |f| %>
    <dt><%= f.search_field :name_or_number_i_cont, placeholder: "告示番号または病名"%></dt>
    <dd><%= f.submit '検索', class: 'search-btn' %></dd>
    <% end %>
  </dl>
</div>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col" , nowrap width=15%> 告示番号</th>
      <th scope="col" , nowrap width=30%>病名</th>
    </tr>
  </thead>

  <tbody>
    <% @diseases.each do |disease| %>
    <tr>
      <td nowrap width=15%><%= link_to disease.number, disease %></td>
      <td nowrap width=30%><%= link_to disease.name, disease %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @diseases %>
<br>
<div style="text-align:center">
  <%= link_to 'ホームに戻る', root_path %> /
  <% if current_user.admin? %>
  <%= link_to '疾患登録', new_disease_path %>
  <% end %></div>

<%#<td><%= link_to '情報', disease %>
<%# <% if current_user.admin? %>
<%# <td><%= link_to 'Edit', edit_disease_path(disease) %>
<%# <td><%= link_to 'Destroy', disease, method: :delete, data: { confirm: 'Are you sure?' } %>
<%# <% end %>

app/views/diseases/new.html.erb
<h2 style="text-align:center">疾患登録</h2>

<%= render 'form', disease: @disease %>

<div style="text-align:center">
  <%= link_to '戻る', diseases_path %>
</div>

app/views/diseases/search.html.erb
<h1>検索結果</h1>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">告示番号</th>
      <th scope="col">名前</th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |disease| %>
    <tr>
      <td align="center"><%= link_to disease.number, disease %></td>
      <td><%= link_to disease.name, disease %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div style="text-align:center">
  <%= link_to '疾患一覧に戻る', diseases_path %>
</div>

app/views/diseases/show.html.erb
<h5 style="text-align:center">告示番号<%= @disease.number %></h5>
<h2 style="text-align:center"><%= @disease.name %></h2>
<br>
<div style="text-align:center">
  <% if @onset.present? %>
  <%= link_to '疾患登録を解除する', onset_path(id: @onset.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
  <%= link_to '疾患を登録する', onsets_path(disease_id: @disease.id), method: :post, class: 'btn btn-primary' %>
  <% end %>

  <%= link_to " 情報一覧", "/diseases/#{@disease.id}/treatments",id: @disease ,class:"btn btn-primary btn-lg far fa-edit "%>

  <%= link_to " 治療費一覧", "/diseases/#{@disease.id}/expenses",id: @disease ,class:"btn btn-primary btn-lg fas fa-comments-dollar"%>
</div>

<!-- コメント入力欄をブログの詳細ページに表示するためのrender上 -->
<%= render partial: 'comments/form', locals: { comment: @comment, disease: @disease } %>

<div style="text-align:center">
  <%= link_to '戻る', diseases_path %></div>

<div id="comments_area">
  <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'comments/index', locals: { comments: @comments, disease: @disease } %>
</div>

<%#= link_to 'Edit', edit_disease_path(@disease) %>
<div style="text-align:center">
  <%= link_to '戻る', diseases_path %>
</div>